"""Read-only five-minute tour of the model mechanics.

Install the package, then run ``python examples/research_walkthrough.py``.
This demonstration writes no files and is intentionally smaller than the paper study.
"""

import argparse
import json
from dataclasses import asdict

from option_hedging.models import (
    black_scholes_call,
    call_delta,
    call_gamma,
    call_theta,
    call_vega,
    crr_call,
    monte_carlo_call,
)
from option_hedging.simulation import simulate_hedge


def build_walkthrough(seed=20260925):
    parameters = dict(spot=100, strike=100, maturity=1, rate=0.03, volatility=0.2)
    pricing = {
        "parameters": parameters,
        "black_scholes": black_scholes_call(**parameters),
        "delta": call_delta(**parameters),
        "gamma": call_gamma(**parameters),
        "vega": call_vega(**parameters),
        "theta": call_theta(**parameters),
        "crr_500_steps": crr_call(**parameters, steps=500),
        "monte_carlo": asdict(monte_carlo_call(**parameters, paths=100_000, seed=seed)),
    }
    hedging = []
    for index, steps in enumerate([12, 52, 126, 252]):
        hedge_seed = seed + index + 1
        for bps in [0, 25]:
            summary = simulate_hedge(
                **parameters,
                steps=steps,
                paths=2000,
                cost_rate=bps / 10_000,
                seed=hedge_seed,
            ).summary()
            hedging.append({"steps": steps, "cost_bps": bps, "seed": hedge_seed, **summary})
    return {"pricing": pricing, "hedging_demo": hedging}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=20260925)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    if args.seed < 0:
        parser.error("--seed must be non-negative")
    report = build_walkthrough(args.seed)
    if args.json:
        print(json.dumps(report, indent=2, allow_nan=False))
        return

    pricing = report["pricing"]
    mc = pricing["monte_carlo"]
    print("1. Analytical and numerical pricing")
    print(f"   Black-Scholes call: {pricing['black_scholes']:.6f}")
    print(f"   Delta: {pricing['delta']:.6f}; Gamma: {pricing['gamma']:.6f}")
    print(f"   Vega: {pricing['vega']:.6f}; Theta: {pricing['theta']:.6f}")
    print(f"   CRR, 500 steps: {pricing['crr_500_steps']:.6f}")
    print(f"   MC, 100000 paths: {mc['price']:.6f}")

    print("\n2. Small hedging demonstration")
    print("   Steps   Cost (bps)      Mean error        RMSE")
    for row in report["hedging_demo"]:
        print(f"   {row['steps']:5d}   {row['cost_bps']:10d}   {row['mean_error']:13.6f}   {row['rmse']:9.6f}")
    print("\nNo files were written. The paper dataset is generated by `python -m option_hedging reproduce`.")


if __name__ == "__main__":
    main()
